### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by CJendantix** [BnuuySolutions/OculusAmeliorated#3]
I don't know the details of this project, but at first it looks promising - if we can get this to run on linux and use it as a backend for ReVive, we might be able to get Oculus exclusives running.

**Comment by codesftdev** [comment]
This project is still under development, just in a private repo. Also, most Oculus exclusives won't work, as they fail the entitlement check.

**Comment by CJendantix** [comment]
Something like Echo VR, though, would, as the new versions have an entitlement patch

**Comment by codesftdev** [comment]
There isn't a reason for Oculus apps to be actively supported as the main purpose of ReLinked is to remove Meta and the dash. You can try using ReVive, but it likely won't be added to ReLinked.

**Comment by CJendantix** [comment]
Sorry, maybe I am confused as to what this project does. I thought that this project was a reimplementation of the Oculus SDK to remove the dependency of the Oculus Store, is this incorrect?

**Comment by codesftdev** [comment]
This project is designed to remove as much Meta things from Oculus Link, and make it an almost-native steam vr headset. The oculus api won't be intentionally supported, and will likely be removed with the full release.

**Comment by CJendantix** [comment]
Okay.
